name: Atualizar Google Sheets

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # 🔥 ESSENCIAL para permitir push

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4   # ✅ versão atualizada

      - name: Baixar CSV do Google Sheets
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1s17Zlq0_zzD1ncRt-yPrLt9pvGqmrPPBIxj_52w_VIs/export?format=csv" -o dados.csv

      - name: Commit e push se houver mudanças
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add dados.csv

          git diff --cached --quiet || git commit -m "Atualizando dados do Sheets"

          git push
